### PR TITLE
Fixes for EIT add some other Descriptors

### PR DESCRIPTION
**Pull request by Diefenthal**

### CODE REVIEW

**Comment by Diefenthal** [comment]
Hi Lewis

In some cases are you right

But in some cases is it better to use the Offset
Any descriptor data (tag + lenght) starts at index +2 in your case
And in some descriptors are fields are not avaible  (Short Extended Event descriptor ) as example
This changes  are working very fine(for me) with feed from dvbs  source

I can you invite to my System to test it self of both Code versions


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Lewis Kirkaldie<mailto:notifications@github.com>
Gesendet: Dienstag, 29. August 2017 21:30
An: Cinegy/TsDecoder<mailto:TsDecoder@noreply.github.com>
Cc: Kay Diefenthal<mailto:KayDiefenthal@hotmail.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Cinegy/TsDecoder] Fixes for EIT add some other Descriptors (#14)


@lewk2 requested changes on this pull request.

try / catch has a performance penalty that can cause severe problems (it is very expensive to throw an exception and catch) so it is generally best to instead catch error conditions and return a null value if it is corrupted. I could live with try / catch here if it is really unavoidable, since it should not be high volume (unlike some other PIDS).

Also, some properties seem to have become INT type, yet are assigned directly against a byte - is this intentional? Elsewhere, i try to maintain the correct type in order to express the intent of constrained values.

Similarly, when working inside the fixed structure element of anything, by convention I use the incrementing maths style (start + X) in the address because this is much easier to debug against the spec (you don't need to do math in your head to spot the offset). I'd prefer you to move back to the old-style to avoid inconsistency,

**Comment by Diefenthal** [comment]
Hi Lewis

The try catch blocks can be removed should working too without it  (if i write test code i add this for me for debug) i had hope that you test first  the Code and if it ok can it be changed to an final Version

For the comments  it is Basic and Need some more Information in it  ( hope i had Thursday many more time for it )

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Lewis Kirkaldie<mailto:notifications@github.com>
Gesendet: Dienstag, 29. August 2017 21:43
An: Cinegy/TsDecoder<mailto:TsDecoder@noreply.github.com>
Cc: Kay Diefenthal<mailto:KayDiefenthal@hotmail.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Cinegy/TsDecoder] Fixes for EIT add some other Descriptors (#14)


@lewk2 approved this pull request.

How very kind to add comments! I did not read every element, but scanned through and this is an excellent contribution.

**Comment by lewk2** [comment]
The try / catch only causes problems really in poor signals. I will merge into a branch and maybe do a general cleanup of such blocks everywhere before moving to master. Good news is the appveyor server likes your changes already!

**Comment by lewk2** [comment]
Hmm... seems only you can choose target branch. Would you kindly reissue pull request against a branch first, and then we can merge into my master later after a few more local checks. This is just because master automates all the way to nuget which can be ... dangerous!

**Comment by Diefenthal** [comment]
Hi Lewis

Should i work on an own branch ?
Or should i send you mails with attachments  with an little description of changes and or ideas.


I have no Problem with it,  i prefer that,that you look into it before it goes final.
Why? Im only hobbiest

and search for an way  to reading the MPEG2TS DVB data for my Sat>Ip Scan Tool (see github Project)Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Lewis Kirkaldie<mailto:notifications@github.com>
Gesendet: Dienstag, 29. August 2017 22:03
An: Cinegy/TsDecoder<mailto:TsDecoder@noreply.github.com>
Cc: Kay Diefenthal<mailto:KayDiefenthal@hotmail.de>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Cinegy/TsDecoder] Fixes for EIT add some other Descriptors (#14)


Hmm... seems only you can choose target branch. Would you kindly reissue pull request against a branch first, and then we can merge into my master later after a few more local checks. This is just because master automates all the way to nuget which can be ... dangerous!

**Comment by lewk2** [comment]
Best practice (although I'm still kinda new to GitHub, and internally we still generally use SVN) is to make a branch for every feature you want to add - so if you want to add comments and docs improvement, make a dedicated branch in your fork for this aspect only, and then request that this fork branch is merged into an equivalent branch against this main project. Then the change can be reviewed discreetly (rather than as above, with three bundled together) and each one accepted and merged singly.

It then is also very easy for me to merge something nice and safe (e.g. comments) quickly and leave behind for more testing or tuning other things.

I have been trying to do 'feature work' these days in a side-branch even when it is just me, and then merge this back in discreetly.

**Comment by lewk2** [comment]
I'm going to merge this anyway, since i will hope to come back and spend a little more time on a general audit and polish shortly, and the implementation of unit tests and such

**Pull request merged**
